SELECT DISTINCT CITY FROM STATION WHERE CITY REGEXP '[a,e,i,o,u]$'
--OR
SELECT DISTINCT CITY FROM STATION 
WHERE CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u'; 